### ISSUE TITLE
Unable to execute "code ." line

### ISSUE THREAD

**Issue by xeyal909** [DevInsideYou/install-scala-env#2]
`
xeyal909@xeyal909-VirtualBox:~$ cd dev
xeyal909@xeyal909-VirtualBox:~/dev$ cd playground/
xeyal909@xeyal909-VirtualBox:~/dev/playground$ sbt test
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.11)
[info] loading settings for project playground-build-build from plugins.sbt ...
[info] loading project definition from /home/xeyal909/dev/playground/project/project
[info] loading settings for project playground-build from plugins.sbt,sbt.sbt ..
[info] loading project definition from /home/xeyal909/dev/playground/project
[info] loading settings for project playground from aliases.sbt,build.sbt,sbt.sbt,scalac.sbt,scalafix.sbt,version.sbt ...
[info] set current project to playground (in build file:/home/xeyal909/dev/playground/)
[info] ╭─────────────────────────────────╮
[info] │     List of defined aliases     │
[info] ├─────────────┬───────────────────┤
[info] │ l | ll | ls │ projects          │
[info] │ cd          │ project           │
[info] │ root        │ cd root           │
[info] │ c           │ compile           │
[info] │ ca          │ compile all       │
[info] │ t           │ test              │
[info] │ r           │ run               │
[info] │ rs          │ reStart           │
[info] │ s           │ reStop            │
[info] │ styleCheck  │ fmt & fix checks  │
[info] │ styleFix    │ fix then fmt      │
[info] │ up2date     │ dependencyUpdates │
[info] ╰─────────────┴───────────────────╯
[info] ExampleSuite:
[info] - hello world (13 milliseconds)
[info] Run completed in 526 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 1 s, completed 5 Oct 2021, 20:19:49
xeyal909@xeyal909-VirtualBox:~/dev/playground$ code .

Command 'code' not found, did you mean:

  command 'tcode' from deb emboss (6.6.0+dfsg-7ubuntu2)
  command 'cde' from deb cde (0.1+git9-g551e54d-1.1build1)
  command 'cdde' from deb cdde (0.3.1-1build1)
  command 'ode' from deb plotutils (2.6-10build1)
  command 'node' from deb nodejs (10.19.0~dfsg-3ubuntu1)

Try: sudo apt install <deb name>
`

**Comment by xeyal909** [comment]
`xeyal909@xeyal909-VirtualBox:~$ cd dev
xeyal909@xeyal909-VirtualBox:~/dev$ cd playground/
xeyal909@xeyal909-VirtualBox:~/dev/playground$ sbt test
[info] welcome to sbt 1.5.5 (Ubuntu Java 11.0.11)
[info] loading settings for project playground-build-build from plugins.sbt ...
[info] loading project definition from /home/xeyal909/dev/playground/project/project
[info] loading settings for project playground-build from plugins.sbt,sbt.sbt ..
[info] loading project definition from /home/xeyal909/dev/playground/project
[info] loading settings for project playground from aliases.sbt,build.sbt,sbt.sbt,scalac.sbt,scalafix.sbt,version.sbt ...
[info] set current project to playground (in build file:/home/xeyal909/dev/playground/)
[info] ╭─────────────────────────────────╮
[info] │     List of defined aliases     │
[info] ├─────────────┬───────────────────┤
[info] │ l | ll | ls │ projects          │
[info] │ cd          │ project           │
[info] │ root        │ cd root           │
[info] │ c           │ compile           │
[info] │ ca          │ compile all       │
[info] │ t           │ test              │
[info] │ r           │ run               │
[info] │ rs          │ reStart           │
[info] │ s           │ reStop            │
[info] │ styleCheck  │ fmt & fix checks  │
[info] │ styleFix    │ fix then fmt      │
[info] │ up2date     │ dependencyUpdates │
[info] ╰─────────────┴───────────────────╯
[info] ExampleSuite:
[info] - hello world (13 milliseconds)
[info] Run completed in 526 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 1 s, completed 5 Oct 2021, 20:19:49
xeyal909@xeyal909-VirtualBox:~/dev/playground$ code .

Command 'code' not found, did you mean:

  command 'tcode' from deb emboss (6.6.0+dfsg-7ubuntu2)
  command 'cde' from deb cde (0.1+git9-g551e54d-1.1build1)
  command 'cdde' from deb cdde (0.3.1-1build1)
  command 'ode' from deb plotutils (2.6-10build1)
  command 'node' from deb nodejs (10.19.0~dfsg-3ubuntu1)

Try: sudo apt install <deb name>
`

**Comment by agilesteel** [comment]
I answered on YouTube. This script installs all the tools necessary for Scala development but it doesn't install any IDE/Editor. The editor I used is vs code. You can get it from [here](https://code.visualstudio.com/).
